# Generated by Django 5.1.3 on 2025-01-23 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitnessapp', '0006_gallery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='title',
        ),
    ]
