apiVersion: apps/v1
kind: Deployment
metadata:
  name: gym-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gym-app
  template:
    metadata:
      labels:
        app: gym-app
    spec:
     containers:
       - name: django
         image: didin8080/gym-app:latest
         ports:
           - containerPort: 8000
