apiVersion: v1
kind: Service
metadata:
  name: gym-service
spec:
  type: NodePort
  selector:
    app: gym-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30111
